spring:
  application:
    name: ayurgyan-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ayurgyan
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Changed to create-drop for development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
  servlet:
    context-path: /api

jwt:
  secret: "ayurgyanSecretKeyForJWTGeneration2024TraditionalMedicine"
  expiration: 86400000

logging:
  level:
    com.ayurgyan: DEBUG
    org.hibernate.SQL: DEBUG